### ISSUE TITLE
Create a getting started / best practice guide

### ISSUE THREAD

**Issue by FWeinb** [FWeinb/grunt-svgstore#22]
The workflow improvements discussed in #16 have an impact on the usage of grunt-svgstore so I would like to update/create a getting started and best practice guide. 

If implementing the proposed idea from #1 the user will have to use css like:

``` css
.svg-sprite{
  width:0;
  height:0;
  visibility:hidden;
}
```

instead of the current `display:none;` to hide the svg sprite to keep `linearGradient` working.
