### ISSUE TITLE
Using in CSS

### ISSUE THREAD

**Issue by adampatarino** [FWeinb/grunt-svgstore#69]
Maybe I'm missing the obvious, but I'm having trouble using the svg sprite file in my css. It works great in html with <use> but I can't get the icons to show up in css. 

I can reference the original svg files directly in css and they work as expected, but the svg sprite returns nothing. 

**Example use // CSS**
This is how I expect it to work, but is blank.

``` css
.icon-heart {
  background: url('path/to/icons.svg#icon-heart');
}
```

using `url('path/to/icon.svg')` is also blank

Ideas? How are you guys using the svg sprite file with your css? Maybe this isn't possible?
